### ISSUE TITLE
Chapter 2 - example requires content-box to align properly 

### ISSUE THREAD

**Issue by pmmueller** [LandonSchropp/unraveling-flexbox#1]
Hi Landon, 
I thoroughly enjoy your book, but have one question about chapter 2, page 34. You use `flex-basis: 22px` to align the elements on the grid and I think this only works correctly with `box-sizing: content-box`. With `border-box` the elements do not really align. 

This is difficult to spot with a 1px border, so I tried a thicker `border-width: 10px` and an adjusted `flex-basis: 40px` (in FF inspector live on [example site](http://example.unravelingflexbox.com/pages/chapter2/twelve_columns.html)). The result is shown on the following screenshots.
# 

border-box - elements do not align properly 

Screenshot no. 1 is with `border-box` (default on example site) and the elements do not align properly: 

![example-border-box](https://cloud.githubusercontent.com/assets/1928205/11849490/74d35d9c-a428-11e5-959c-40b28f4a7a6a.jpg)
# 

content-box - all is fine 

For screenshot no. 2 I have only changed the box-model to `content-box` and now everything is fine: 

![example-content-box](https://cloud.githubusercontent.com/assets/1928205/11849512/8ad06b1c-a428-11e5-90c9-a21d177e500e.jpg)

To align the elements you'd have to double the value for `border-width`. With `flex-basis: 60px` it works fine.  

Maybe I'm missing something, but I think the example stylesheet should contain a rule like `section, div { box-sizing: content-box; }` or the value should be changed to `flex-basis: 24px` (twice the `border-width`, although I don't really understand why that works).

**Comment by LandonSchropp** [comment]
Hey @pmmueller, thanks for taking the time to write up such a detailed account of this bug. You're definitely right, the content is slightly misaligned, and setting the `box-sizing` to `border-box` seems to fix the problem.

I dug into the [flexbox spec](http://www.w3.org/TR/css-flexbox-1/#flex-basis-property), and the only mention I could find of `box-sizing` is this:

> <‘width’> For all other values, flex-basis is resolved the same way as width in horizontal writing modes [CSS21]: percentage values of flex-basis are resolved against the flex item’s containing block, i.e. its flex container, and if that containing block’s size is indefinite, the result is the same as a main size of auto. Similarly, flex-basis determines the size of the content box, unless otherwise specified such as by box-sizing [CSS3UI].

So, it seems like the value of `box-sizing` can _override_ `flex-basis`. If I had to guess, I'd say that by using `content-box`, we're giving flexbox permission to include the borders in its size calculations. Without it, it sets the size of the content and then tacks on the borders as an after thought (which would account for the `20px` difference between `flex-basis: 40px` and `flex-basis: 60px`.

Thanks again for taking the time to write this up. I'll get it fixed right away.
